run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocritic
    - revive
    - unparam
    - misspell
    - dogsled
    - whitespace
    - bodyclose

linters-settings:
  govet:
    shadow: true
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: blank-imports
        severity: warning
      - name: line-length-limit
        arguments: [120]
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
